//package com.linkpulse.bookmark_ai;
//
//import org.slf4j.Logger;
//import org.slf4j.LoggerFactory;
//import org.springframework.stereotype.Service;
//
//import java.util.List;
//
///**
// * Service Layer: Contains all the business logic for bookmarks.
// *
// * THE LAYERED ARCHITECTURE:
// *
// *   Controller  →  receives HTTP requests, validates input, returns responses
// *       ↓
// *   Service     →  business logic, orchestration, rules
// *       ↓
// *   Repository  →  data access (talks to database)
// *
// * WHY SEPARATE CONTROLLER AND SERVICE?
// * 1. Controller handles HTTP concerns (request/response, status codes)
// * 2. Service handles business concerns (rules, validation, orchestration)
// * 3. Same service can be called from a controller, a Kafka consumer,
// *    or a scheduled job — the business logic is reusable.
// *
// * Example: "Create a bookmark" logic is in BookmarkService.
// * Today, the controller calls it. Next month, a Kafka consumer
// * will also call it. The logic stays in one place.
// *
// * DEPENDENCY INJECTION:
// * Notice how we declare BookmarkRepository as a constructor parameter.
// * Spring automatically provides an instance when creating BookmarkService.
// * This is called "Constructor Injection" — the recommended way in Spring.
// *
// * WHY CONSTRUCTOR INJECTION (not @Autowired on fields)?
// * 1. Makes dependencies explicit — you see them in the constructor
// * 2. The object is always in a valid state (all deps available)
// * 3. Easier to test — pass mock dependencies in the constructor
// * 4. Fields can be final — immutable, thread-safe
// */
//@Service // Marks this class as a Spring-managed service bean
//public class BookmarkService {
//
//    // Logger: Always use SLF4J (Simple Logging Facade for Java).
//    // It's the standard logging API that works with any logging backend
//    // (Logback, Log4j, etc.). Spring Boot uses Logback by default.
//    private static final Logger log = LoggerFactory.getLogger(BookmarkService.class);
//
//    // This field is final — set once in constructor, never changed.
//    // Spring injects the actual implementation at runtime.
//    private final BookmarkRepository bookmarkRepository;
//
//    // Constructor injection: Spring provides the BookmarkRepository.
//    // When Spring creates BookmarkService, it sees this constructor
//    // needs a BookmarkRepository, finds one in its context, and
//    // passes it in. You never write "new BookmarkRepository()".
//    public BookmarkService(BookmarkRepository bookmarkRepository) {
//        this.bookmarkRepository = bookmarkRepository;
//    }
//
//    /**
//     * Create a new bookmark.
//     *
//     * WHAT HAPPENS HERE:
//     * 1. Convert the DTO (what client sent) into an Entity (what DB stores)
//     * 2. Save to database
//     * 3. Convert the saved Entity back to a response DTO
//     * 4. Return the response
//     *
//     * WHY CONVERT DTO → Entity → DTO?
//     * Request DTO might have different fields than the Entity.
//     * After saving, the Entity has an ID (generated by DB) and
//     * timestamps that the client needs to see in the response.
//     */
//    public BookmarkResponse createBookmark(CreateBookmarkRequest request) {
//        log.debug("Creating bookmark for URL: {}", request.url());
//        // ↑ Use {} placeholders, not string concatenation.
//        // log.debug("URL: " + request.url()) is BAD because the string
//        // is built even if DEBUG logging is disabled. {} is lazy.
//
//        // Convert request DTO → Entity
//        Bookmark bookmark = new Bookmark(
//                request.url(),
//                request.title(),
//                request.description()
//        );
//
//        // Save to database. JPA generates:
//        //   INSERT INTO bookmarks (url, title, description, created_at, updated_at)
//        //   VALUES (?, ?, ?, ?, ?)
//        // and returns the entity with the generated ID.
//        Bookmark savedBookmark = bookmarkRepository.save(bookmark);
//        log.info("Bookmark created with id={}", savedBookmark.getId());
//
//        // Convert Entity → Response DTO
//        return BookmarkResponse.from(savedBookmark);
//    }
//
//    /**
//     * Get all bookmarks.
//     *
//     * NOTE: This returns ALL bookmarks — fine for now, but won't
//     * scale when you have thousands. In Weekend 2, you'll add
//     * pagination using Spring's Pageable interface.
//     */
//    public List<BookmarkResponse> getAllBookmarks() {
//        log.debug("Fetching all bookmarks");
//
//        return bookmarkRepository.findAll()
//                .stream()                       // Convert List to Stream
//                .map(BookmarkResponse::from)    // Convert each Entity → DTO
//                .toList();                      // Collect back to List
//        // ↑ This is a method reference: BookmarkResponse::from
//        // It's shorthand for: bookmark -> BookmarkResponse.from(bookmark)
//    }
//
//    /**
//     * Get a bookmark by its ID.
//     *
//     * Returns null if not found. The controller will handle
//     * returning a 404 status code.
//     *
//     * DESIGN CHOICE: return null vs throw exception
//     * - Returning null: simple, controller decides what to do
//     * - Throwing exception: more "Java-like", use @ControllerAdvice
//     * We'll use exceptions — it's cleaner for error handling.
//     * See GlobalExceptionHandler.java.
//     */
//    public BookmarkResponse getBookmarkById(Long id) {
//        log.debug("Fetching bookmark with id={}", id);
//
//        // findById returns Optional<Bookmark>.
//        // Optional forces you to handle "not found" explicitly.
//        // .orElseThrow() throws NoSuchElementException if not found.
//        // Our GlobalExceptionHandler catches this and returns 404.
//        Bookmark bookmark = bookmarkRepository.findById(id)
//                .orElseThrow(() -> {
//                    log.warn("Bookmark not found with id={}", id);
//                    return new BookmarkNotFoundException(id);
//                });
//
//        return BookmarkResponse.from(bookmark);
//    }
//
//    /**
//     * Delete a bookmark by ID.
//     *
//     * We verify it exists first. If not, throw an exception.
//     * Why not just call deleteById() directly?
//     * Because deleteById() silently does nothing if the ID
//     * doesn't exist — the client would think it succeeded.
//     * We want to return 404 if the bookmark doesn't exist.
//     */
//    public void deleteBookmark(Long id) {
//        log.debug("Deleting bookmark with id={}", id);
//
//        if (!bookmarkRepository.existsById(id)) {
//            throw new BookmarkNotFoundException(id);
//        }
//
//        bookmarkRepository.deleteById(id);
//        log.info("Bookmark deleted with id={}", id);
//    }
//}
